// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct Calendar {
  var id: String
  var title: String
  var color: Int64
  var sourceName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Calendar? {
    let id = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let color = pigeonVar_list[2] as! Int64
    let sourceName: String? = nilOrValue(pigeonVar_list[3])

    return Calendar(
      id: id,
      title: title,
      color: color,
      sourceName: sourceName
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      color,
      sourceName,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Event {
  var id: String? = nil
  var title: String
  var startDate: Int64
  var endDate: Int64
  var timeZone: String
  var calendarId: String
  var description: String? = nil
  var url: String? = nil
  var alarms: [Alarm?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Event? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let title = pigeonVar_list[1] as! String
    let startDate = pigeonVar_list[2] as! Int64
    let endDate = pigeonVar_list[3] as! Int64
    let timeZone = pigeonVar_list[4] as! String
    let calendarId = pigeonVar_list[5] as! String
    let description: String? = nilOrValue(pigeonVar_list[6])
    let url: String? = nilOrValue(pigeonVar_list[7])
    let alarms = pigeonVar_list[8] as! [Alarm?]

    return Event(
      id: id,
      title: title,
      startDate: startDate,
      endDate: endDate,
      timeZone: timeZone,
      calendarId: calendarId,
      description: description,
      url: url,
      alarms: alarms
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      startDate,
      endDate,
      timeZone,
      calendarId,
      description,
      url,
      alarms,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Alarm {
  var minutes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Alarm? {
    let minutes = pigeonVar_list[0] as! Int64

    return Alarm(
      minutes: minutes
    )
  }
  func toList() -> [Any?] {
    return [
      minutes
    ]
  }
}

private class CalendarActionsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return Calendar.fromList(self.readValue() as! [Any?])
    case 130:
      return Event.fromList(self.readValue() as! [Any?])
    case 131:
      return Alarm.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CalendarActionsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Calendar {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? Event {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? Alarm {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CalendarActionsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CalendarActionsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CalendarActionsPigeonCodecWriter(data: data)
  }
}

class CalendarActionsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CalendarActionsPigeonCodec(readerWriter: CalendarActionsPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CalendarActions {
  func requestCalendarAccess(completion: @escaping (Result<Bool, Error>) -> Void)
  func createCalendar(title: String, color: Int64, completion: @escaping (Result<Calendar, Error>) -> Void)
  func retrieveCalendars(onlyWritableCalendars: Bool, completion: @escaping (Result<[Calendar], Error>) -> Void)
  func createOrUpdateEvent(flutterEvent: Event, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CalendarActionsSetup {
  static var codec: FlutterStandardMessageCodec { CalendarActionsPigeonCodec.shared }
  /// Sets up an instance of `CalendarActions` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CalendarActions?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let requestCalendarAccessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_calendar_connect.CalendarActions.requestCalendarAccess\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestCalendarAccessChannel.setMessageHandler { _, reply in
        api.requestCalendarAccess { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestCalendarAccessChannel.setMessageHandler(nil)
    }
    let createCalendarChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_calendar_connect.CalendarActions.createCalendar\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createCalendarChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let titleArg = args[0] as! String
        let colorArg = args[1] as! Int64
        api.createCalendar(title: titleArg, color: colorArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createCalendarChannel.setMessageHandler(nil)
    }
    let retrieveCalendarsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_calendar_connect.CalendarActions.retrieveCalendars\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      retrieveCalendarsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let onlyWritableCalendarsArg = args[0] as! Bool
        api.retrieveCalendars(onlyWritableCalendars: onlyWritableCalendarsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      retrieveCalendarsChannel.setMessageHandler(nil)
    }
    let createOrUpdateEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_calendar_connect.CalendarActions.createOrUpdateEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createOrUpdateEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let flutterEventArg = args[0] as! Event
        api.createOrUpdateEvent(flutterEvent: flutterEventArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createOrUpdateEventChannel.setMessageHandler(nil)
    }
  }
}
