codecov:
  branch: main
  disable_default_path_fixes: true

coverage:
  range: 60..80
  round: down
  precision: 2

  status:
    project:
      flutter:
        enabled: yes
        target: 80%
        threshold: 1%
      ios:
        enabled: yes
        target: 80%
        threshold: 1%
      android:
        enabled: no # Disabled while android is not behaving with codecov
        target: 80%
        threshold: 1%

fixes:
  - "Users/runner/work/eventide/eventide/::"

ignore:
  - "**/*.g.*"
  - "example/"
  - "**/EasyEventStore.swift"
  - "**/PermissionHandler.swift"