codecov:
  branch: main
  disable_default_path_fixes: true

coverage:
  range: 60..80
  round: down
  precision: 2

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project:
      default:
        enabled: yes
        target: 80%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target

fixes:
  - "Users/runner/work/eventide/eventide/::"

ignore:
  - "**/*.g.*"
  - "example/"
  - "**/EasyEventStore.swift"
  - "**/PermissionHandler.swift"