name: eventide
description: "Provides a easy-to-use flutter interface to access & modify native device calendars (iOS & Android)"
version: 0.10.2
repository: https://github.com/sncf-connect-tech/eventide
topics:
  - flutter
  - calendar
  - api
  - native
  - eventide

keywords:
  - flutter
  - calendar
  - api
  - native
  - eventide
  - sncf
  - plugin
  - mobile
  - event management
  - calendar integration
  - cross-platform
  - reminders
  - event scheduling
  - date management
  - time management
  - flutter plugin
  - calendar events
  - calendar API
  - iOS calendar
  - Android calendar
  - iOS 17 write-only permission

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.2.0
  timezone: ^0.10.0
  mocktail: ^1.0.4
  clock: ^1.1.1
  import_sorter: ^4.6.0

flutter:
  plugin:
    platforms:
      android:
        package: sncf.connect.tech.eventide
        pluginClass: EventidePlugin
      ios:
        pluginClass: EventidePlugin