// Autogenerated from Pigeon (v24.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package sncf.connect.tech.eventide

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class Calendar (
  val id: String,
  val title: String,
  val color: Long,
  val isWritable: Boolean,
  val account: Account
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Calendar {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val color = pigeonVar_list[2] as Long
      val isWritable = pigeonVar_list[3] as Boolean
      val account = pigeonVar_list[4] as Account
      return Calendar(id, title, color, isWritable, account)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      color,
      isWritable,
      account,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Event (
  val id: String,
  val calendarId: String,
  val title: String,
  val isAllDay: Boolean,
  val startDate: Long,
  val endDate: Long,
  val reminders: List<Long>,
  val attendees: List<Attendee>,
  val description: String? = null,
  val url: String? = null,
  val rRule: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Event {
      val id = pigeonVar_list[0] as String
      val calendarId = pigeonVar_list[1] as String
      val title = pigeonVar_list[2] as String
      val isAllDay = pigeonVar_list[3] as Boolean
      val startDate = pigeonVar_list[4] as Long
      val endDate = pigeonVar_list[5] as Long
      val reminders = pigeonVar_list[6] as List<Long>
      val attendees = pigeonVar_list[7] as List<Attendee>
      val description = pigeonVar_list[8] as String?
      val url = pigeonVar_list[9] as String?
      val rRule = pigeonVar_list[10] as String?
      return Event(id, calendarId, title, isAllDay, startDate, endDate, reminders, attendees, description, url, rRule)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      calendarId,
      title,
      isAllDay,
      startDate,
      endDate,
      reminders,
      attendees,
      description,
      url,
      rRule,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Account (
  val name: String,
  val type: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Account {
      val name = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as String
      return Account(name, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      type,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Attendee (
  val name: String,
  val email: String,
  val type: Long,
  val role: Long,
  val status: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Attendee {
      val name = pigeonVar_list[0] as String
      val email = pigeonVar_list[1] as String
      val type = pigeonVar_list[2] as Long
      val role = pigeonVar_list[3] as Long
      val status = pigeonVar_list[4] as Long
      return Attendee(name, email, type, role, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      email,
      type,
      role,
      status,
    )
  }
}
private open class CalendarApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Calendar.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Event.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Account.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Attendee.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is Calendar -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is Event -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is Account -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is Attendee -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CalendarApi {
  fun requestCalendarPermission(callback: (Result<Boolean>) -> Unit)
  fun createCalendar(title: String, color: Long, localAccountName: String, callback: (Result<Calendar>) -> Unit)
  fun retrieveCalendars(onlyWritableCalendars: Boolean, fromLocalAccountName: String?, callback: (Result<List<Calendar>>) -> Unit)
  fun deleteCalendar(calendarId: String, callback: (Result<Unit>) -> Unit)
  fun createEvent(calendarId: String, title: String, startDate: Long, endDate: Long, isAllDay: Boolean, description: String?, url: String?, rRule: String?, callback: (Result<Event>) -> Unit)
  fun retrieveEvents(calendarId: String, startDate: Long, endDate: Long, callback: (Result<List<Event>>) -> Unit)
  fun deleteEvent(eventId: String, callback: (Result<Unit>) -> Unit)
  fun createReminder(reminder: Long, eventId: String, callback: (Result<Event>) -> Unit)
  fun deleteReminder(reminder: Long, eventId: String, callback: (Result<Event>) -> Unit)
  fun createAttendee(eventId: String, name: String, email: String, role: Long, type: Long, callback: (Result<Event>) -> Unit)
  fun deleteAttendee(eventId: String, email: String, callback: (Result<Event>) -> Unit)

  companion object {
    /** The codec used by CalendarApi. */
    val codec: MessageCodec<Any?> by lazy {
      CalendarApiPigeonCodec()
    }
    /** Sets up an instance of `CalendarApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CalendarApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.requestCalendarPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestCalendarPermission{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.createCalendar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String
            val colorArg = args[1] as Long
            val localAccountNameArg = args[2] as String
            api.createCalendar(titleArg, colorArg, localAccountNameArg) { result: Result<Calendar> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.retrieveCalendars$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val onlyWritableCalendarsArg = args[0] as Boolean
            val fromLocalAccountNameArg = args[1] as String?
            api.retrieveCalendars(onlyWritableCalendarsArg, fromLocalAccountNameArg) { result: Result<List<Calendar>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.deleteCalendar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            api.deleteCalendar(calendarIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.createEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val titleArg = args[1] as String
            val startDateArg = args[2] as Long
            val endDateArg = args[3] as Long
            val isAllDayArg = args[4] as Boolean
            val descriptionArg = args[5] as String?
            val urlArg = args[6] as String?
            val rRuleArg = args[7] as String?
            api.createEvent(calendarIdArg, titleArg, startDateArg, endDateArg, isAllDayArg, descriptionArg, urlArg, rRuleArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.retrieveEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val startDateArg = args[1] as Long
            val endDateArg = args[2] as Long
            api.retrieveEvents(calendarIdArg, startDateArg, endDateArg) { result: Result<List<Event>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.deleteEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventIdArg = args[0] as String
            api.deleteEvent(eventIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.createReminder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reminderArg = args[0] as Long
            val eventIdArg = args[1] as String
            api.createReminder(reminderArg, eventIdArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.deleteReminder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reminderArg = args[0] as Long
            val eventIdArg = args[1] as String
            api.deleteReminder(reminderArg, eventIdArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.createAttendee$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventIdArg = args[0] as String
            val nameArg = args[1] as String
            val emailArg = args[2] as String
            val roleArg = args[3] as Long
            val typeArg = args[4] as Long
            api.createAttendee(eventIdArg, nameArg, emailArg, roleArg, typeArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.deleteAttendee$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventIdArg = args[0] as String
            val emailArg = args[1] as String
            api.deleteAttendee(eventIdArg, emailArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
