// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package sncf.connect.tech.eventide

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CalendarApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class Calendar (
  val id: String,
  val title: String,
  val color: Long,
  val isWritable: Boolean,
  val account: Account
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Calendar {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val color = pigeonVar_list[2] as Long
      val isWritable = pigeonVar_list[3] as Boolean
      val account = pigeonVar_list[4] as Account
      return Calendar(id, title, color, isWritable, account)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      color,
      isWritable,
      account,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Calendar
    return CalendarApiPigeonUtils.deepEquals(this.id, other.id) && CalendarApiPigeonUtils.deepEquals(this.title, other.title) && CalendarApiPigeonUtils.deepEquals(this.color, other.color) && CalendarApiPigeonUtils.deepEquals(this.isWritable, other.isWritable) && CalendarApiPigeonUtils.deepEquals(this.account, other.account)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.id)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.title)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.color)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.isWritable)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.account)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Event (
  val id: String,
  val calendarId: String,
  val title: String,
  val isAllDay: Boolean,
  val startDate: Long,
  val endDate: Long,
  val reminders: List<Long>,
  val attendees: List<Attendee>,
  val description: String? = null,
  val url: String? = null,
  val location: String? = null,
  val recurrenceRule: String? = null,
  val originalInstanceTime: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Event {
      val id = pigeonVar_list[0] as String
      val calendarId = pigeonVar_list[1] as String
      val title = pigeonVar_list[2] as String
      val isAllDay = pigeonVar_list[3] as Boolean
      val startDate = pigeonVar_list[4] as Long
      val endDate = pigeonVar_list[5] as Long
      val reminders = pigeonVar_list[6] as List<Long>
      val attendees = pigeonVar_list[7] as List<Attendee>
      val description = pigeonVar_list[8] as String?
      val url = pigeonVar_list[9] as String?
      val location = pigeonVar_list[10] as String?
      val recurrenceRule = pigeonVar_list[11] as String?
      val originalInstanceTime = pigeonVar_list[12] as Long?
      return Event(id, calendarId, title, isAllDay, startDate, endDate, reminders, attendees, description, url, location, recurrenceRule, originalInstanceTime)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      calendarId,
      title,
      isAllDay,
      startDate,
      endDate,
      reminders,
      attendees,
      description,
      url,
      location,
      recurrenceRule,
      originalInstanceTime,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Event
    return CalendarApiPigeonUtils.deepEquals(this.id, other.id) && CalendarApiPigeonUtils.deepEquals(this.calendarId, other.calendarId) && CalendarApiPigeonUtils.deepEquals(this.title, other.title) && CalendarApiPigeonUtils.deepEquals(this.isAllDay, other.isAllDay) && CalendarApiPigeonUtils.deepEquals(this.startDate, other.startDate) && CalendarApiPigeonUtils.deepEquals(this.endDate, other.endDate) && CalendarApiPigeonUtils.deepEquals(this.reminders, other.reminders) && CalendarApiPigeonUtils.deepEquals(this.attendees, other.attendees) && CalendarApiPigeonUtils.deepEquals(this.description, other.description) && CalendarApiPigeonUtils.deepEquals(this.url, other.url) && CalendarApiPigeonUtils.deepEquals(this.location, other.location) && CalendarApiPigeonUtils.deepEquals(this.recurrenceRule, other.recurrenceRule) && CalendarApiPigeonUtils.deepEquals(this.originalInstanceTime, other.originalInstanceTime)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.id)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.calendarId)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.title)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.isAllDay)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.startDate)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.endDate)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.reminders)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.attendees)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.description)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.url)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.location)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.recurrenceRule)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.originalInstanceTime)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Account (
  val id: String,
  val name: String,
  val type: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Account {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val type = pigeonVar_list[2] as String
      return Account(id, name, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Account
    return CalendarApiPigeonUtils.deepEquals(this.id, other.id) && CalendarApiPigeonUtils.deepEquals(this.name, other.name) && CalendarApiPigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.id)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.name)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.type)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Attendee (
  val name: String,
  val email: String,
  val type: Long,
  val role: Long,
  val status: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Attendee {
      val name = pigeonVar_list[0] as String
      val email = pigeonVar_list[1] as String
      val type = pigeonVar_list[2] as Long
      val role = pigeonVar_list[3] as Long
      val status = pigeonVar_list[4] as Long
      return Attendee(name, email, type, role, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      email,
      type,
      role,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Attendee
    return CalendarApiPigeonUtils.deepEquals(this.name, other.name) && CalendarApiPigeonUtils.deepEquals(this.email, other.email) && CalendarApiPigeonUtils.deepEquals(this.type, other.type) && CalendarApiPigeonUtils.deepEquals(this.role, other.role) && CalendarApiPigeonUtils.deepEquals(this.status, other.status)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.name)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.email)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.type)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.role)
    result = 31 * result + CalendarApiPigeonUtils.deepHash(this.status)
    return result
  }
}
private open class CalendarApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Calendar.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Event.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Account.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Attendee.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is Calendar -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is Event -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is Account -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is Attendee -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CalendarApi {
  fun createCalendar(title: String, color: Long, account: Account?, callback: (Result<Calendar>) -> Unit)
  fun updateCalendar(calendarId: String, title: String, color: Long, callback: (Result<Calendar>) -> Unit)
  fun retrieveCalendars(onlyWritableCalendars: Boolean, account: Account?, callback: (Result<List<Calendar>>) -> Unit)
  fun retrieveAccounts(callback: (Result<List<Account>>) -> Unit)
  fun deleteCalendar(calendarId: String, callback: (Result<Unit>) -> Unit)
  fun createEvent(calendarId: String, title: String, startDate: Long, endDate: Long, isAllDay: Boolean, description: String?, url: String?, location: String?, reminders: List<Long>?, recurrenceRule: String?, callback: (Result<Event>) -> Unit)
  fun updateEvent(eventId: String, calendarId: String, title: String, startDate: Long, endDate: Long, isAllDay: Boolean, description: String?, url: String?, location: String?, reminders: List<Long>?, recurrenceRule: String?, span: String, originalInstanceTime: Long?, callback: (Result<Event>) -> Unit)
  fun createEventInDefaultCalendar(title: String, startDate: Long, endDate: Long, isAllDay: Boolean, description: String?, url: String?, location: String?, reminders: List<Long>?, recurrenceRule: String?, callback: (Result<Unit>) -> Unit)
  fun createEventThroughNativePlatform(title: String?, startDate: Long?, endDate: Long?, isAllDay: Boolean?, description: String?, url: String?, location: String?, reminders: List<Long>?, recurrenceRule: String?, callback: (Result<Unit>) -> Unit)
  fun retrieveEvents(calendarId: String, startDate: Long, endDate: Long, callback: (Result<List<Event>>) -> Unit)
  fun deleteEvent(eventId: String, span: String, originalInstanceTime: Long?, callback: (Result<Unit>) -> Unit)
  fun createReminder(reminder: Long, eventId: String, callback: (Result<Event>) -> Unit)
  fun deleteReminder(reminder: Long, eventId: String, callback: (Result<Event>) -> Unit)
  fun createAttendee(eventId: String, name: String, email: String, role: Long, type: Long, callback: (Result<Event>) -> Unit)
  fun deleteAttendee(eventId: String, email: String, callback: (Result<Event>) -> Unit)

  companion object {
    /** The codec used by CalendarApi. */
    val codec: MessageCodec<Any?> by lazy {
      CalendarApiPigeonCodec()
    }
    /** Sets up an instance of `CalendarApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CalendarApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.createCalendar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String
            val colorArg = args[1] as Long
            val accountArg = args[2] as Account?
            api.createCalendar(titleArg, colorArg, accountArg) { result: Result<Calendar> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.updateCalendar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val titleArg = args[1] as String
            val colorArg = args[2] as Long
            api.updateCalendar(calendarIdArg, titleArg, colorArg) { result: Result<Calendar> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.retrieveCalendars$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val onlyWritableCalendarsArg = args[0] as Boolean
            val accountArg = args[1] as Account?
            api.retrieveCalendars(onlyWritableCalendarsArg, accountArg) { result: Result<List<Calendar>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.retrieveAccounts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.retrieveAccounts{ result: Result<List<Account>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.deleteCalendar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            api.deleteCalendar(calendarIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CalendarApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.createEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val titleArg = args[1] as String
            val startDateArg = args[2] as Long
            val endDateArg = args[3] as Long
            val isAllDayArg = args[4] as Boolean
            val descriptionArg = args[5] as String?
            val urlArg = args[6] as String?
            val locationArg = args[7] as String?
            val remindersArg = args[8] as List<Long>?
            val recurrenceRuleArg = args[9] as String?
            api.createEvent(calendarIdArg, titleArg, startDateArg, endDateArg, isAllDayArg, descriptionArg, urlArg, locationArg, remindersArg, recurrenceRuleArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.updateEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventIdArg = args[0] as String
            val calendarIdArg = args[1] as String
            val titleArg = args[2] as String
            val startDateArg = args[3] as Long
            val endDateArg = args[4] as Long
            val isAllDayArg = args[5] as Boolean
            val descriptionArg = args[6] as String?
            val urlArg = args[7] as String?
            val locationArg = args[8] as String?
            val remindersArg = args[9] as List<Long>?
            val recurrenceRuleArg = args[10] as String?
            val spanArg = args[11] as String
            val originalInstanceTimeArg = args[12] as Long?
            api.updateEvent(eventIdArg, calendarIdArg, titleArg, startDateArg, endDateArg, isAllDayArg, descriptionArg, urlArg, locationArg, remindersArg, recurrenceRuleArg, spanArg, originalInstanceTimeArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.createEventInDefaultCalendar$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String
            val startDateArg = args[1] as Long
            val endDateArg = args[2] as Long
            val isAllDayArg = args[3] as Boolean
            val descriptionArg = args[4] as String?
            val urlArg = args[5] as String?
            val locationArg = args[6] as String?
            val remindersArg = args[7] as List<Long>?
            val recurrenceRuleArg = args[8] as String?
            api.createEventInDefaultCalendar(titleArg, startDateArg, endDateArg, isAllDayArg, descriptionArg, urlArg, locationArg, remindersArg, recurrenceRuleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CalendarApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.createEventThroughNativePlatform$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String?
            val startDateArg = args[1] as Long?
            val endDateArg = args[2] as Long?
            val isAllDayArg = args[3] as Boolean?
            val descriptionArg = args[4] as String?
            val urlArg = args[5] as String?
            val locationArg = args[6] as String?
            val remindersArg = args[7] as List<Long>?
            val recurrenceRuleArg = args[8] as String?
            api.createEventThroughNativePlatform(titleArg, startDateArg, endDateArg, isAllDayArg, descriptionArg, urlArg, locationArg, remindersArg, recurrenceRuleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CalendarApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.retrieveEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val calendarIdArg = args[0] as String
            val startDateArg = args[1] as Long
            val endDateArg = args[2] as Long
            api.retrieveEvents(calendarIdArg, startDateArg, endDateArg) { result: Result<List<Event>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.deleteEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventIdArg = args[0] as String
            val spanArg = args[1] as String
            val originalInstanceTimeArg = args[2] as Long?
            api.deleteEvent(eventIdArg, spanArg, originalInstanceTimeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CalendarApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.createReminder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reminderArg = args[0] as Long
            val eventIdArg = args[1] as String
            api.createReminder(reminderArg, eventIdArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.deleteReminder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reminderArg = args[0] as Long
            val eventIdArg = args[1] as String
            api.deleteReminder(reminderArg, eventIdArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.createAttendee$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventIdArg = args[0] as String
            val nameArg = args[1] as String
            val emailArg = args[2] as String
            val roleArg = args[3] as Long
            val typeArg = args[4] as Long
            api.createAttendee(eventIdArg, nameArg, emailArg, roleArg, typeArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eventide.CalendarApi.deleteAttendee$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventIdArg = args[0] as String
            val emailArg = args[1] as String
            api.deleteAttendee(eventIdArg, emailArg) { result: Result<Event> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CalendarApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CalendarApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
