name: eventide_example_native_only
description: "Demonstrates how to use the eventide plugin."
publish_to: 'none'
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  eventide:
    path: ../../../
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true