name: Android Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  android-tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Verify Flutter Installation
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build and test
        run: |
          ./example/android/gradlew testDebugUnitTest jacocoTestReport -p ./example/android/

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          files: ./android/build/reports/jacocoTestReport.xml