name: Flutter Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  flutter-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Verify Flutter Installation
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze --fatal-infos
        working-directory: lib

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          